# Generated by Django 3.2 on 2021-04-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210414_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('1', 'Teacher'), ('2', 'Student')], default=1, max_length=10),
        ),
    ]
